### ISSUE TITLE
Compilation of µWebSockets has failed.Please install a supported C++17 compiler, git and/or update node and reinstall the module 'eiows'.

### ISSUE THREAD

**Issue by jasonhis** [mmdevries/eiows#25]
I am getting this error:

```
/src/app/node_modules/eiows/dist/eiows.js:30
})();
  ^
Error: Error: Cannot find module './eiows_v19.3.0'
Require stack:
- /src/app/node_modules/eiows/dist/eiows.js
- /src/app/build/core/socket.core.js
- /src/app/build/core/pos/printOrder.core.js
- /src/app/build/services/posOrder.service.js
- /src/app/build/routes/posRoute.js
- /src/app/build/init/expressInit.js
- /src/app/build/app.js

Compilation of µWebSockets has failed.Please install a supported C++17 compiler, git and/or update node and reinstall the module 'eiows'.
    at /src/app/node_modules/eiows/dist/eiows.js:27:15
    at Object.<anonymous> (/src/app/node_modules/eiows/dist/eiows.js:30:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/src/src/core/socket.core.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
```

Here is my Dockerfile

```bash
FROM node:19.3.0-alpine

# for eiows
RUN apk add build-base libc6-compat git

WORKDIR /src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

CMD [ "node", "build/app.js" ]

```

What additional packages I should install to get it work?  Thank you!

**Comment by mmdevries** [comment]
Sorry for the late reply. You probably already solved this but you need to install python3 as well.

```
FROM node:19.3.0-alpine

# for eiows
RUN apk add build-base libc6-compat git python3

WORKDIR /src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

CMD [ "node", "build/app.js" ]

```

**Comment by Avasam** [comment]
I have all those as well but I'm still getting the following error:
```
[nodemon] starting `yarn babel-node src/index.js`

/code/node_modules/eiows/dist/eiows.js:27

        throw new Error(e.toString() + '\n\nCompilation of µWebSockets has failed.' +

        ^


Error: Error: Cannot find module './eiows_v22.20.0'

Require stack:

- /code/node_modules/eiows/dist/eiows.js

- /code/node_modules/engine.io/lib/server.js

- /code/node_modules/engine.io/lib/engine.io.js

- /code/node_modules/socket.io/dist/index.js

- /code/src/index.js


Compilation of µWebSockets has failed.Please install a supported C++17 compiler, git and/or update node and reinstall the module 'eiows'.

    at /code/node_modules/eiows/dist/eiows.js:27:15

    at Object.<anonymous> (/code/node_modules/eiows/dist/eiows.js:30:3)

    at Module._compile (node:internal/modules/cjs/loader:1706:14)

    at Module._compile (/code/node_modules/pirates/lib/index.js:99:24)

    at node:internal/modules/cjs/loader:1839:10

    at Object.newLoader [as .js] (/code/node_modules/pirates/lib/index.js:104:7)

    at Module.load (node:internal/modules/cjs/loader:1441:32)

    at Function._load (node:internal/modules/cjs/loader:1263:12)

    at TracingChannel.traceSync (node:diagnostics_channel:322:14)

    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)


Node.js v22.20.0
```

Dockerfile:
```
FROM node:lts-alpine
RUN corepack enable

# make + git needed to build eiows. python3 + libc6-compat for µWebSockets on Alpine
# https://github.com/mmdevries/eiows/issues/25#issuecomment-2444222253
# https://github.com/nodejs/docker-node#nodealpine
RUN apk add --no-cache build-base git python3 libc6-compat

RUN mkdir /code
WORKDIR /code

COPY package.json yarn.lock .yarnrc.yml /code/

RUN yarn install --immutable

CMD ["yarn", "dev"]
```

Relevant docker-compose.yml section:
```yml
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/code
      - /code/node_modules
```

`yarn dev` is just `nodemon --exec 'yarn babel-node src/index.js' -e '.js'`

Currently using `eiows@8.2.0`
